### ISSUE TITLE
Compile error: Missing skip_eps_strategy() for the pinned_allocator

### ISSUE THREAD

**Issue by aklein3** [ptal/turbo#25]
Turbo no longer compiles using the pinned_allocator.

```
/home/alanu/talbot/turbo/include/hybrid_dive_and_solve.hpp(371): error: 
class "lala::SplitStrategy<lala::PIR<lala::VStore<Itv, battery::pinned_allocator>, 
UniqueLightAlloc<battery::standard_allocator, 0UL>>, battery::standard_allocator>" 
has no member "skip_eps_strategy"

          cube.split->skip_eps_strategy();
                      ^
1 error detected in the compilation of "/home/alanu/talbot/turbo/src/turbo.cpp".
```

**Comment by ptal** [comment]
Thanks for reporting the bug. I'm going to look into it ASAP. Note that the current version on main has some bugs; I'm actively looking into them.

**Comment by ptal** [comment]
Hi Alan :) Actually, you would need to checkout a version first: `git checkout v1.2.8`. Otherwise it is going to try to compile with the version 1.2.8 of the dependencies, while you are using the "main" version of Turbo.
